### ISSUE TITLE
Is this not working anymore? 😅 

### ISSUE THREAD

**Issue by yarub123** [KiPSOFT/nostr-nip05-service#1]
I sent the DM to you for the automatic verification but idk if it's working. I didn't hear anything back. The instructions were a bit tricky 🙃

Thank you anyway!

**Comment by KiPSOFT** [comment]
Hi, what's your name in registration form ?

**Comment by yarub123** [comment]
@KiPSOFT Damn, I don't remember which I used.... It's probably the email with "newman or newm or newman.jacb123."

If it's not on there I can just make a new one. This is my name on Nostr, I messaged you a few times, from Iris, and from astral.ninja and I think even Amethyst on android lol. 

Name on Nostr is "Juced01"

**Comment by KiPSOFT** [comment]
Your name is not in list. Please try again add new request in page. https://nostrprotocol.net

**Comment by yarub123** [comment]
@KiPSOFT Ok my dear brother. Thank you for the response. Apologies for the late reply. I have done it again. Lmk if it showed up on your end

**Comment by yarub123** [comment]
Oops nvm @KiPSOFT disregard all these messages. I just registered on Iris a few minutes ago it was a little faster and I like their URL it's a bit shorter. Thanks anyways.
